### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by kohltje** [iMarkus/Sonoff-Somfy-HomeAssistant#1]
Hi,

first of all, thanx for the insight and great documentation :)

Question:
Doesn't it brick my remote because of the high payload of power send to the device?

thanx :)

**Comment by iMarkus** [comment]
Hi,
thanks.

See: [arendst/Sonoff-Tasmota](https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-4CH-and-4CH-Pro)

> Compared to the 4CH the main differences/improvements of the 4CH Pro are:
> 
> Relays are isolated from mains and can each switch their own circuit (mains or low voltage).
> 

There is no high payload / power send to the device, it works potential free and is the same as if you press the button on the remote.

Regards,
iMarkus
